services:
  - type: web
    name: swadsetu-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
      - key: MONGO_URI
        fromContext: parameter
      - key: JWT_SECRET
        fromContext: parameter
